var calculateData = function(age, gender) {
    var symptoms = '<div class="acronym__description-suggestion">Tell your doctor if you experience any of the following symptoms: fever, chest pain, shortness of breath or difficulty breathing, nausea, vomiting, dizziness, weight gain/loss, changes in bowel or habits, muscle or joint pains, or unexplained bleeding or bruising.</div>',
        immunizations,
        medications = '<div class="acronym__description-suggestion"><p>Tell your doctor about any and all medications you are taking. This includes prescription medications, over-the-counter medications (e.g., Tylenol, ibuprofen, aspirin, etc.), herbal remedies, complementary medicines, and vitamin supplements.</p><p>Remember to ask for refills of any medications, as needed.<p></div>',
        procedures, lifestyle,
        exercise = '<div class="acronym__description-suggestion"><p class="bold">For Overall Cardiovascular Health:</p><p>At least 30 minutes of moderate-intensity aerobic activity (e.g., brisk walking) on 5 or more days every week<p>OR</p><p>At least 25 minutes of vigorous aerobic activity (e.g., running) on 3 or more days every week</p><p>AND</p><p>Moderate&hyphen; to high&hyphen;intensity muscle&hyphen;strengthening activity on at least 2 days every week for additional health benefits.</p><p class="bold">For Lowering Blood Pressure and Cholesterol</p><p>At least 40 minutes of moderate- to vigorous-intensity aerobic activity 3 or 4 times per week</p></div>';

    if (age >= 19 && age <= 21 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years. If you are pregnant, you should get a Tdap vaccine during the 3rd trimester of every pregnancy to help protect your babies from pertussis (whooping cough). </p><p><span class="bold">HPV vaccine</span>, 3 doses</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p><p><span class="bold">Meningococcal vaccine</span>: First-year college students up through age 21 who are living in residence halls should be vaccinated if you have not already been vaccinated on or after your 16th birthday</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">For sexually active women:</span> first Pap test for cervical cancer screening starting at age 21, chlamydia and gonorrhea testing every year through age 24.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 19 && age <= 21 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">HPV vaccine</span>, 3 doses</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p><p><span class="bold">Meningococcal vaccine</span>: First-year college students up through age 21 who are living in residence halls should be vaccinated if you have not already been vaccinated on or after your 16th birthday</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 22 && age <= 26 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years. If you are pregnant, you should get a Tdap vaccine during the 3rd trimester of every pregnancy to help protect your babies from pertussis (whooping cough). </p><p><span class="bold">HPV vaccine</span>, 3 doses</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">Cervical cancer screening</span>: Pap test every 3 years.</p><p><span class="bold">Chlamydia and Gonorrhea</span>: test every year for sexually active women through age 24.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 22 && age <= 26 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">HPV vaccine</span>, 3 doses</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 27 && age <= 49 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years. If you are pregnant, you should get a Tdap vaccine during the 3rd trimester of every pregnancy to help protect your babies from pertussis (whooping cough). </p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years, beginning at age 45.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years, beginning at age 45.</p><p><span class="bold">Cervical cancer screening</span>: Pap test every 3 years.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 27 && age <= 49 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years, beginning at age 45.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years, beginning at age 45.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 50 && age <= 59 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every 3-5 years</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Cervical cancer screening</span>: Pap test every 3 years.</p><p><span class="bold">Breast cancer screening</span>: mammogram every 2 years</p><p><span class="bold">Colon cancer screening</span>: colonoscopy at age 50 and then every 10 years, OR annual fecal occult blood test (FOBT) plus sigmoidoscopy every 5 years, OR sigmoidoscopy every 5 years, OR double-contrast barium enema every 5 years. Talk with your doctor about the best method for you.</p><p><span class="bold">Hepatits C</span>: test at least one time during adulthood if you were born 1945-1965.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 50 && age <= 59 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Prostate cancer screening</span>: discuss with your doctor.</p><p><span class="bold">Colon cancer screening</span>: colonoscopy at age 50 and then every 10 years, OR annual fecal occult blood test (FOBT) plus sigmoidoscopy every 5 years, OR sigmoidoscopy every 5 years, OR double-contrast barium enema every 5 years. Talk with your doctor about the best method for you.</p><p><span class="bold">Hepatits C</span>: test at least one time during adulthood if you were born 1945-1965.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 60 && age <= 64 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Shingles (Zoster) vaccine</span>, 1 dose at age 60 or older</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Cervical cancer screening</span>: Pap test every 3 years.</p><p><span class="bold">Breast cancer screening</span>: mammogram every 2 years</p><p><span class="bold">Colon cancer screening</span>: colonoscopy at age 50 and then every 10 years, OR annual fecal occult blood test (FOBT) plus sigmoidoscopy every 5 years, OR sigmoidoscopy every 5 years, OR double-contrast barium enema every 5 years. Talk with your doctor about the best method for you.</p><p><span class="bold">Hepatits C</span>: test at least one time during adulthood if you were born 1945-1965.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 60 && age <= 64 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Shingles (Zoster) vaccine</span>, 1 dose at age 60 or older</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Prostate cancer screening</span>: discuss with your doctor.</p><p><span class="bold">Colon cancer screening</span>: colonoscopy at age 50 and then every 10 years, OR annual fecal occult blood test (FOBT) plus sigmoidoscopy every 5 years, OR sigmoidoscopy every 5 years, OR double-contrast barium enema every 5 years. Talk with your doctor about the best method for you.</p><p><span class="bold">Hepatits C</span>: test at least one time during adulthood if you were born 1945-1965.</p><p><span class="bold">HIV:</span> test at least one time during adulthood (through age 64).</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 65 && age <= 74 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Pneumococcal vaccine</span>, 1 dose at age 65 or older</p><p><span class="bold">Shingles (Zoster) vaccine</span>, 1 dose at age 60 or older</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years through age 79. After age 79, discuss with your doctor.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Vision and hearing checks</span>: every year.</p><p><span class="bold">Bone density test</span>: recommended for women ages 65 and older.</p><p><span class="bold">Cervical cancer screening</span>: Pap test is not generally recommended for women ages 65 and older who have had adequate prior screening and are not otherwise at high risk for cervical cancer.</p><p><span class="bold">Breast cancer screening</span>: mammogram every 2 years. For women ages 75 and older, discuss optional screening with your doctor</p><p><span class="bold">Colon cancer screening</span>: colonoscopy at age 50 and then every 10 years, or annual fecal occult blood test (FOBT) plus sigmoidoscopy every 5 years, or sigmoidoscopy every 5 years, or double-contrast barium enema every 5 years. Talk with your doctor about the best method for you. For women ages 75 and older, regular screening is not generally recommended. If you wish to continue screening, talk with your doctor.</p><p><span class="bold">Hepatits C</span>: test at least one time during adulthood if you were born 1945-1965.</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 65 && age <= 74 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Pneumococcal vaccine</span>, 1 dose at age 65 or older</p><p><span class="bold">Shingles (Zoster) vaccine</span>, 1 dose at age 60 or older</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Vision and hearing checks</span>: every year.</p><p><span class="bold">Prostate cancer screening</span>: discuss with your doctor.</p><p><span class="bold">Colon cancer screening</span>: colonoscopy at age 50 and then every 10 years, or annual fecal occult blood test (FOBT) plus sigmoidoscopy every 5 years, or sigmoidoscopy every 5 years, or double-contrast barium enema every 5 years. Talk with your doctor about the best method for you. For men ages 75 and older, regular screening is not generally recommended. If you wish to continue screening, talk with your doctor.</p><p><span class="bold">Abdominal aortic aneurysm (AAA) screening</span>: one-time screening for men ages 65-75 who have ever smoked.</p><p><span class="bold">Hepatits C</span>: test at least one time during adulthood if you were born 1945-1965.</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 75 && gender === 'female') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Pneumococcal vaccine</span>, 1 dose at age 65 or older</p><p><span class="bold">Shingles (Zoster) vaccine</span>, 1 dose at age 60 or older</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years through age 79. After age 79, discuss with your doctor.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Vision and hearing checks</span>: every year.</p><p><span class="bold">Bone density test</span>: recommended for women ages 65 and older.</p><p><span class="bold">Cervical cancer screening</span>: Pap test is not generally recommended for women ages 65 and older who have had adequate prior screening and are not otherwise at high risk for cervical cancer.</p><p><span class="bold">Breast cancer screening</span>: Discuss optional screening by mammogram with your doctor.</p><p><span class="bold">Colon cancer screening</span>: Regular screening is not generally recommended. If you wish to continue screening, talk with your doctor.</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For women ages 21 and older, limit alcohol consumption to 1 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    } else if (age >= 75 && gender === 'male') {
        immunizations = '<div class="acronym__description-suggestion"><p><span class="bold">Flu vaccine</span> every year</p><p><span class="bold">Tetanus-diphtheria (Td)</span> or <span class="bold">Tetanus-diphtheria-acellular pertussis (TdaP)</span> booster every 10 years.</p><p><span class="bold">Pneumococcal vaccine</span>, 1 dose at age 65 or older</p><p><span class="bold">Shingles (Zoster) vaccine</span>, 1 dose at age 60 or older</p><p><span class="bold">Varicella vaccine</span>, 2 doses (unless previously vaccinated or you have a history of varicella/chicken-pox or herpes zoster/shingles)</p></div>';
        procedures = '<div class="acronym__description-suggestion"><p><span class="bold">Blood pressure:</span> check at every acute/non-acute medical encounter and at least once every year</p><p><span class="bold">Cholesterol</span>: check at least once every 5 years.</p><p><span class="bold">Diabetes screening</span>: at least once every 3 years.</p><p><span class="bold">Vision and hearing checks</span>: every year.</p><p><span class="bold">Prostate cancer screening</span>: discuss with your doctor.</p><p><span class="bold">Colon cancer screening</span>: Regular screening is not generally recommended. If you wish to continue screening, talk with your doctor.</p></div>';
        lifestyle = '<div class="acronym__description-suggestion"><p><span class="bold">Smoking</span> is a major risk factor for a number of health conditions, including high blood pressure, diabetes, and cardiovascular disease. Speak with your doctor if you are interested in quitting smoking.</p><p><span class="bold">Alcohol:</span> For men ages 21 and older, limit alcohol consumption to 2 or fewer drinks per day.</p><p class="bold">1 drink = 1/2oz or 15mL ethanol (e.g., 12oz beer, 5oz wine, 1.5oz 80-proof whiskey)</p><p><span class="bold">Diet:</span> Adopt a diet rich in fruits and vegetables. Reduce intake of saturated and total fats. Reduce dietary salt (sodium) intake to 2.4g per day.</p></div>';

    }

    $('.replacement-class').html("<table class='acronym-explanation__table'><tbody><tr class='acronym-explanation__acronym'><td class='acronym-explanation__acronym-letter'>S</td><td class='acronym-explanation__acronym-description'><div class='acronym__description-heading'>Symptoms</div><div class='acronym__description-subtext'>What is the reason for your appointment today?</div>" + symptoms + "</td></tr><tr class='acronym-explanation__acronym'><td class='acronym-explanation__acronym-letter'>I</td><td class='acronym-explanation__acronym-description'><div class='acronym__description-heading'>Immunizations</div>" + immunizations +"</td></tr><tr class='acronym-explanation__acronym'><td class='acronym-explanation__acronym-letter'>M</td><td class='acronym-explanation__acronym-description'><div class='acronym__description-heading'>Medications &sol; Refills</div>" + medications + "</td></tr><tr class='acronym-explanation__acronym'><td class='acronym-explanation__acronym-letter'>P</td><td class='acronym-explanation__acronym-description'><div class='acronym__description-heading'>Procedures &sol; Screening Tests</div>" + procedures + "</td></tr><tr class='acronym-explanation__acronym'><td class='acronym-explanation__acronym-letter'>L</td><td class='acronym-explanation__acronym-description'><div class='acronym__description-heading'>Lifestyle Modifications</div>" + lifestyle +"</td></tr><tr class='acronym-explanation__acronym'><td class='acronym-explanation__acronym-letter'>E</td><td class='acronym-explanation__acronym-description'><div class='acronym__description-heading'>Exercise</div>" + exercise +"</td></tr></tbody></table>");
    $('.replacement-class').addClass('appointment');
};

$(document).ready(function() {
    $('[data-form-submit]').on('click', function() {
        var $age = $('[data-age-input]').val(),
            $gender = $('[data-gender-input]:checked').val();
        calculateData($age, $gender);

        return false;
    });
});